version: "3.9"

services:
  ts:
    build:
      context: .
      dockerfile: Dockerfile-ts
    ports:
      - "3000:3000"
    networks:
      - my-network
  zil:
    build:
      context: .
      dockerfile: Dockerfile-zil
    ports:
      - "8080:8080"
    networks:
      - my-network
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
      - beat
    networks:
      - my-network
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - my-network

  redis:
    image: redis:latest
    networks:
      - my-network

  celery:
    build: .
    command: celery -A cosmos worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - beat
    networks:
      - my-network
  beat:
    build: .
    command: celery -A cosmos beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - my-network

volumes:
  postgres_data:



networks:
    my-network: