# Generated by Django 4.1.7 on 2023-03-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllReceiverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=100)),
                ('tag', models.CharField(default='', max_length=100)),
                ('memo', models.CharField(default='', max_length=100)),
                ('network', models.CharField(default='cardano', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllSenderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=100)),
                ('network', models.CharField(default='cardano', max_length=100)),
                ('signing_key', models.JSONField(blank=True, null=True)),
                ('seed', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllCreateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='0', max_length=100)),
                ('transaction_hash', models.CharField(default='rejected', max_length=500)),
                ('network', models.CharField(default='cardano', max_length=100)),
                ('symbol', models.CharField(default='ada', max_length=50)),
                ('midKey', models.CharField(default='', max_length=100)),
                ('key', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='withdraw.allsenderwallet')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='withdraw.allreceiverwallet')),
            ],
        ),
    ]
