# Generated by Django 4.1.7 on 2023-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsenderwallet',
            name='seed',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='allsenderwallet',
            name='signing_key',
            field=models.JSONField(default='', max_length=300),
        ),
    ]
