# Generated by Django 4.1.7 on 2023-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_alter_allsenderwallet_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsenderwallet',
            name='signing_key',
            field=models.JSONField(default='{}', max_length=300),
        ),
    ]
