# Generated by Django 4.1.7 on 2023-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_alter_allsenderwallet_signing_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allsenderwallet',
            old_name='seed',
            new_name='cosmos_seed',
        ),
        migrations.RemoveField(
            model_name='allsenderwallet',
            name='signing_key',
        ),
        migrations.AddField(
            model_name='allsenderwallet',
            name='cardano_signing_key',
            field=models.JSONField(default=dict),
        ),
    ]
