# Generated by Django 4.1.7 on 2023-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0004_rename_seed_allsenderwallet_cosmos_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsenderwallet',
            name='cardano_signing_key',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='allsenderwallet',
            name='cosmos_seed',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
