# Generated by Django 4.1.7 on 2023-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0005_alter_allsenderwallet_cardano_signing_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsenderwallet',
            name='cardano_signing_key',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allsenderwallet',
            name='cosmos_seed',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
