# Generated by Django 4.1.7 on 2023-03-05 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('withdraw', '0006_alter_allsenderwallet_cardano_signing_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsenderwallet',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
