# Generated by Django 4.1.7 on 2023-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0008_alter_allsenderwallet_cardano_signing_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsenderwallet',
            name='cardano_signing_key',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
