# Generated by Django 4.1.7 on 2023-03-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0009_alter_allsenderwallet_cardano_signing_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allsenderwallet',
            name='cardano_signing_key',
        ),
        migrations.RemoveField(
            model_name='allsenderwallet',
            name='cosmos_seed',
        ),
        migrations.AddField(
            model_name='allsenderwallet',
            name='private_key',
            field=models.JSONField(default=''),
        ),
    ]
