# Generated by Django 4.1.6 on 2023-02-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushableTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SenderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('seed', models.CharField(max_length=300)),
                ('private_key', models.CharField(max_length=300)),
                ('account_number', models.IntegerField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('sync_mode', models.CharField(default='sync', max_length=100)),
                ('chain_id', models.CharField(default='cosmoshub-4', max_length=100)),
                ('receiver_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.receiverwallet')),
                ('sender_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.senderwallet')),
            ],
        ),
    ]
