# Generated by Django 4.1.6 on 2023-02-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0002_rename_sender_address_createtransaction_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderwallet',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
