# Generated by Django 4.1.6 on 2023-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_alter_senderwallet_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderwallet',
            name='private_key',
            field=models.BinaryField(),
        ),
    ]
