# Generated by Django 4.1.6 on 2023-02-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_alter_senderwallet_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderwallet',
            name='memo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
