# Generated by Django 4.1.6 on 2023-02-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_senderwallet_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverwallet',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
