# Generated by Django 4.1.6 on 2023-02-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_receiverwallet_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PushableTransaction',
        ),
        migrations.AlterField(
            model_name='createtransaction',
            name='from_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='transfer.senderwallet'),
        ),
        migrations.AddField(
            model_name='pushedtransaction',
            name='create_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.createtransaction'),
        ),
    ]
