# Generated by Django 4.1.6 on 2023-02-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_pushedtransaction_delete_pushabletransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtransaction',
            name='from_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.senderwallet'),
        ),
    ]
