# Generated by Django 4.1.6 on 2023-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_alter_createtransaction_from_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderwallet',
            name='memo',
        ),
        migrations.AddField(
            model_name='receiverwallet',
            name='memo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
