# Generated by Django 4.1.6 on 2023-02-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_remove_senderwallet_memo_receiverwallet_memo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PushedTransaction',
            new_name='PublishTransaction',
        ),
    ]
