# Generated by Django 4.1.6 on 2023-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0016_remove_publishtransaction_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtransaction',
            name='amount',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
