# Generated by Django 4.1.6 on 2023-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0017_createtransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtransaction',
            name='transaction_hash',
            field=models.CharField(default='rejected', max_length=500),
        ),
        migrations.DeleteModel(
            name='PublishTransaction',
        ),
    ]
