# Generated by Django 4.1.6 on 2023-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0018_createtransaction_transaction_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtransaction',
            name='transaction_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
