# Generated by Django 4.1.7 on 2023-02-25 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0019_createtransaction_transaction_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverwallet',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
