# Generated by Django 4.1.6 on 2023-02-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createtransaction',
            old_name='sender_address',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='createtransaction',
            old_name='receiver_address',
            new_name='to_address',
        ),
        migrations.RenameField(
            model_name='receiverwallet',
            old_name='receiver_address',
            new_name='to_address',
        ),
        migrations.RenameField(
            model_name='senderwallet',
            old_name='address',
            new_name='from_address',
        ),
    ]
